Add project side panel
QuantStack/jupybase pull request #5
Opened 2024-07-22 09:11 UTC by DenisaCG

2024-07-22 09:25 UTC, trungleduc commented on src/projectPanel.tsx
> +export class ProjectPanel extends React.Component<IProjectProps> {
I think we should move to modern React with function components instead of using class components.  
https://react.dev/reference/react/Component

2024-07-22 12:19 UTC, DenisaCG commented on src/projectPanel.tsx
> +export class ProjectPanel extends React.Component<IProjectProps> {
Thanks for the suggestion! The latest commit switches to function components.

2024-08-01 22:49 UTC, trungleduc requested changes

2024-08-01 22:49 UTC, trungleduc commented on src/index.ts
> +    const content = result!.data.data[0].content;
you should wrap this call in a try-catch block, for example

```suggestion
    let content = {name: '', shortDesc : '',  buildEnv : '',  kernelEnv : '', lockfile: '', dependencies : [] }
    try{
        const result = await apiClient?.get(url);
        content = result!.data.data[0].content;
    } catch {
     // handle error here
    }

```

2024-08-01 22:49 UTC, trungleduc commented on src/index.ts
> +      factory: async () => projectData
no need a factory pattern here anymore since you used the API client provided by `IJupybaseClient`

2024-08-01 22:49 UTC, trungleduc commented on src/index.ts
> +}
these interfaces can be defined in the `token.ts` file to avoid importing from `index.ts`

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +  };
these functions can be defined outside of the component

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +
this should be wrapped inside a `useCallback` hook

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +          onClick={() => onProfileClick()}
```suggestion
          onClick={onProfileClick}
```

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +          onClick={() => onProfileClick()}
same for other locations

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +  const renderToolbar = () => {
Can these render* functions be converted into standalone React components?

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +    function onBuildEnvironmentClick() {
I would avoid creating nested functions inside a React component since they will be re-created on every render unless they are wrapped inside a `useCallback` hook

2024-08-01 22:49 UTC, trungleduc commented on src/projectPanel.tsx
> +      <div className={panelWrapperClass}>
Using `gap`(https://developer.mozilla.org/en-US/docs/Web/CSS/gap) might be better than `<br>` to add the gap between components.

2024-08-01 22:49 UTC, trungleduc commented on src/projectWidget.tsx
> +      <div>
the `div` is needed?

2024-08-01 22:49 UTC, trungleduc commented on src/projectWidget.tsx
> +export namespace Private {
exporting a namespace named `Private` is inconsistent.

2024-08-01 22:49 UTC, trungleduc commented on src/sharingProjectDialog.tsx
> +  const updateAvailableUsersList = (user: { name: string; email: string }) => {
This needs to be wrapped inside `useCallback` hook, same for other functions

2024-08-01 22:49 UTC, trungleduc commented on src/sharingProjectDialog.tsx
> +    setProjectCollaborators(collaborators);
```suggestion
    setProjectCollaborators([...projectCollaborators, addedProjectCollaborator]);
```

2024-08-01 22:49 UTC, trungleduc commented on src/sharingProjectDialog.tsx
> +      <br></br>
generally, I would avoid using the `br` tag.

2024-08-02 11:16 UTC, DenisaCG commented on src/index.ts
> +      factory: async () => projectData
I would prefer to continue using the `IProjectInfo` interface structure.

2024-08-02 11:44 UTC, DenisaCG commented
Thanks for the review, @trungleduc!

2024-08-02 12:22 UTC, trungleduc approved these changes

2024-08-02 12:22 UTC, trungleduc commented
Thanks

2024-08-02 12:27 UTC, merged